      - name: Build
        run: |
          ls
          xcrun --sdk iphoneos clang -arch arm64 -dynamiclib -fobjc-arc \
            -miphoneos-version-min=14.0 \
            -framework UIKit \
            -framework Foundation \
            *.m \
            -o Ryumax.dylib
